version: "3"
services:
  streaming-ms-front:
    build:
      dockerfile: Dockerfile
      context: ./
    image: streaming-ms-front
    container_name: streaming-ms-front
    volumes:
      - /app/node_modules #도커 /app/node_modules는 맵핑을 따로 안해주겠다.
      - ./:/app # 로컬에 있는 모든 파일을 맵핑
    ports:
      - "8080:8080"
    stdin_open: true